/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppXerclerRouteImport } from './routes/_app.xercler'
import { Route as AppUiDemoRouteImport } from './routes/_app.ui-demo'
import { Route as AppTedarukculerRouteImport } from './routes/_app.tedarukculer'
import { Route as AppSatisRouteImport } from './routes/_app.satis'
import { Route as AppMallarRouteImport } from './routes/_app.mallar'
import { Route as AppIscilarRouteImport } from './routes/_app.iscilar'
import { Route as AppHesabatlarRouteImport } from './routes/_app.hesabatlar'
import { Route as AppGunSonuRouteImport } from './routes/_app.gun-sonu'
import { Route as AppBorclarRouteImport } from './routes/_app.borclar'
import { Route as AppAyarlarRouteImport } from './routes/_app.ayarlar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppXerclerRoute = AppXerclerRouteImport.update({
  id: '/xercler',
  path: '/xercler',
  getParentRoute: () => AppRoute,
} as any)
const AppUiDemoRoute = AppUiDemoRouteImport.update({
  id: '/ui-demo',
  path: '/ui-demo',
  getParentRoute: () => AppRoute,
} as any)
const AppTedarukculerRoute = AppTedarukculerRouteImport.update({
  id: '/tedarukculer',
  path: '/tedarukculer',
  getParentRoute: () => AppRoute,
} as any)
const AppSatisRoute = AppSatisRouteImport.update({
  id: '/satis',
  path: '/satis',
  getParentRoute: () => AppRoute,
} as any)
const AppMallarRoute = AppMallarRouteImport.update({
  id: '/mallar',
  path: '/mallar',
  getParentRoute: () => AppRoute,
} as any)
const AppIscilarRoute = AppIscilarRouteImport.update({
  id: '/iscilar',
  path: '/iscilar',
  getParentRoute: () => AppRoute,
} as any)
const AppHesabatlarRoute = AppHesabatlarRouteImport.update({
  id: '/hesabatlar',
  path: '/hesabatlar',
  getParentRoute: () => AppRoute,
} as any)
const AppGunSonuRoute = AppGunSonuRouteImport.update({
  id: '/gun-sonu',
  path: '/gun-sonu',
  getParentRoute: () => AppRoute,
} as any)
const AppBorclarRoute = AppBorclarRouteImport.update({
  id: '/borclar',
  path: '/borclar',
  getParentRoute: () => AppRoute,
} as any)
const AppAyarlarRoute = AppAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/ayarlar': typeof AppAyarlarRoute
  '/borclar': typeof AppBorclarRoute
  '/gun-sonu': typeof AppGunSonuRoute
  '/hesabatlar': typeof AppHesabatlarRoute
  '/iscilar': typeof AppIscilarRoute
  '/mallar': typeof AppMallarRoute
  '/satis': typeof AppSatisRoute
  '/tedarukculer': typeof AppTedarukculerRoute
  '/ui-demo': typeof AppUiDemoRoute
  '/xercler': typeof AppXerclerRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ayarlar': typeof AppAyarlarRoute
  '/borclar': typeof AppBorclarRoute
  '/gun-sonu': typeof AppGunSonuRoute
  '/hesabatlar': typeof AppHesabatlarRoute
  '/iscilar': typeof AppIscilarRoute
  '/mallar': typeof AppMallarRoute
  '/satis': typeof AppSatisRoute
  '/tedarukculer': typeof AppTedarukculerRoute
  '/ui-demo': typeof AppUiDemoRoute
  '/xercler': typeof AppXerclerRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ayarlar': typeof AppAyarlarRoute
  '/_app/borclar': typeof AppBorclarRoute
  '/_app/gun-sonu': typeof AppGunSonuRoute
  '/_app/hesabatlar': typeof AppHesabatlarRoute
  '/_app/iscilar': typeof AppIscilarRoute
  '/_app/mallar': typeof AppMallarRoute
  '/_app/satis': typeof AppSatisRoute
  '/_app/tedarukculer': typeof AppTedarukculerRoute
  '/_app/ui-demo': typeof AppUiDemoRoute
  '/_app/xercler': typeof AppXerclerRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ayarlar'
    | '/borclar'
    | '/gun-sonu'
    | '/hesabatlar'
    | '/iscilar'
    | '/mallar'
    | '/satis'
    | '/tedarukculer'
    | '/ui-demo'
    | '/xercler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ayarlar'
    | '/borclar'
    | '/gun-sonu'
    | '/hesabatlar'
    | '/iscilar'
    | '/mallar'
    | '/satis'
    | '/tedarukculer'
    | '/ui-demo'
    | '/xercler'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/ayarlar'
    | '/_app/borclar'
    | '/_app/gun-sonu'
    | '/_app/hesabatlar'
    | '/_app/iscilar'
    | '/_app/mallar'
    | '/_app/satis'
    | '/_app/tedarukculer'
    | '/_app/ui-demo'
    | '/_app/xercler'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/xercler': {
      id: '/_app/xercler'
      path: '/xercler'
      fullPath: '/xercler'
      preLoaderRoute: typeof AppXerclerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ui-demo': {
      id: '/_app/ui-demo'
      path: '/ui-demo'
      fullPath: '/ui-demo'
      preLoaderRoute: typeof AppUiDemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tedarukculer': {
      id: '/_app/tedarukculer'
      path: '/tedarukculer'
      fullPath: '/tedarukculer'
      preLoaderRoute: typeof AppTedarukculerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis': {
      id: '/_app/satis'
      path: '/satis'
      fullPath: '/satis'
      preLoaderRoute: typeof AppSatisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mallar': {
      id: '/_app/mallar'
      path: '/mallar'
      fullPath: '/mallar'
      preLoaderRoute: typeof AppMallarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iscilar': {
      id: '/_app/iscilar'
      path: '/iscilar'
      fullPath: '/iscilar'
      preLoaderRoute: typeof AppIscilarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hesabatlar': {
      id: '/_app/hesabatlar'
      path: '/hesabatlar'
      fullPath: '/hesabatlar'
      preLoaderRoute: typeof AppHesabatlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gun-sonu': {
      id: '/_app/gun-sonu'
      path: '/gun-sonu'
      fullPath: '/gun-sonu'
      preLoaderRoute: typeof AppGunSonuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borclar': {
      id: '/_app/borclar'
      path: '/borclar'
      fullPath: '/borclar'
      preLoaderRoute: typeof AppBorclarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ayarlar': {
      id: '/_app/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AppAyarlarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAyarlarRoute: typeof AppAyarlarRoute
  AppBorclarRoute: typeof AppBorclarRoute
  AppGunSonuRoute: typeof AppGunSonuRoute
  AppHesabatlarRoute: typeof AppHesabatlarRoute
  AppIscilarRoute: typeof AppIscilarRoute
  AppMallarRoute: typeof AppMallarRoute
  AppSatisRoute: typeof AppSatisRoute
  AppTedarukculerRoute: typeof AppTedarukculerRoute
  AppUiDemoRoute: typeof AppUiDemoRoute
  AppXerclerRoute: typeof AppXerclerRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAyarlarRoute: AppAyarlarRoute,
  AppBorclarRoute: AppBorclarRoute,
  AppGunSonuRoute: AppGunSonuRoute,
  AppHesabatlarRoute: AppHesabatlarRoute,
  AppIscilarRoute: AppIscilarRoute,
  AppMallarRoute: AppMallarRoute,
  AppSatisRoute: AppSatisRoute,
  AppTedarukculerRoute: AppTedarukculerRoute,
  AppUiDemoRoute: AppUiDemoRoute,
  AppXerclerRoute: AppXerclerRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
