/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QeydiyyatRouteImport } from './routes/qeydiyyat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HesabBlokluRouteImport } from './routes/hesab-bloklu'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppXerclerRouteImport } from './routes/_app.xercler'
import { Route as AppTedarukculerRouteImport } from './routes/_app.tedarukculer'
import { Route as AppSatisRouteImport } from './routes/_app.satis'
import { Route as AppPanelRouteImport } from './routes/_app.panel'
import { Route as AppMusterilerRouteImport } from './routes/_app.musteriler'
import { Route as AppMallarRouteImport } from './routes/_app.mallar'
import { Route as AppIscilarRouteImport } from './routes/_app.iscilar'
import { Route as AppHesabatlarRouteImport } from './routes/_app.hesabatlar'
import { Route as AppGunSonuRouteImport } from './routes/_app.gun-sonu'
import { Route as AppBorclarRouteImport } from './routes/_app.borclar'
import { Route as AppAyarlarRouteImport } from './routes/_app.ayarlar'
import { Route as AppMallarIdRouteImport } from './routes/_app.mallar_.$id'

const QeydiyyatRoute = QeydiyyatRouteImport.update({
  id: '/qeydiyyat',
  path: '/qeydiyyat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HesabBlokluRoute = HesabBlokluRouteImport.update({
  id: '/hesab-bloklu',
  path: '/hesab-bloklu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppXerclerRoute = AppXerclerRouteImport.update({
  id: '/xercler',
  path: '/xercler',
  getParentRoute: () => AppRoute,
} as any)
const AppTedarukculerRoute = AppTedarukculerRouteImport.update({
  id: '/tedarukculer',
  path: '/tedarukculer',
  getParentRoute: () => AppRoute,
} as any)
const AppSatisRoute = AppSatisRouteImport.update({
  id: '/satis',
  path: '/satis',
  getParentRoute: () => AppRoute,
} as any)
const AppPanelRoute = AppPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AppRoute,
} as any)
const AppMusterilerRoute = AppMusterilerRouteImport.update({
  id: '/musteriler',
  path: '/musteriler',
  getParentRoute: () => AppRoute,
} as any)
const AppMallarRoute = AppMallarRouteImport.update({
  id: '/mallar',
  path: '/mallar',
  getParentRoute: () => AppRoute,
} as any)
const AppIscilarRoute = AppIscilarRouteImport.update({
  id: '/iscilar',
  path: '/iscilar',
  getParentRoute: () => AppRoute,
} as any)
const AppHesabatlarRoute = AppHesabatlarRouteImport.update({
  id: '/hesabatlar',
  path: '/hesabatlar',
  getParentRoute: () => AppRoute,
} as any)
const AppGunSonuRoute = AppGunSonuRouteImport.update({
  id: '/gun-sonu',
  path: '/gun-sonu',
  getParentRoute: () => AppRoute,
} as any)
const AppBorclarRoute = AppBorclarRouteImport.update({
  id: '/borclar',
  path: '/borclar',
  getParentRoute: () => AppRoute,
} as any)
const AppAyarlarRoute = AppAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AppRoute,
} as any)
const AppMallarIdRoute = AppMallarIdRouteImport.update({
  id: '/mallar_/$id',
  path: '/mallar/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hesab-bloklu': typeof HesabBlokluRoute
  '/login': typeof LoginRoute
  '/qeydiyyat': typeof QeydiyyatRoute
  '/ayarlar': typeof AppAyarlarRoute
  '/borclar': typeof AppBorclarRoute
  '/gun-sonu': typeof AppGunSonuRoute
  '/hesabatlar': typeof AppHesabatlarRoute
  '/iscilar': typeof AppIscilarRoute
  '/mallar': typeof AppMallarRoute
  '/musteriler': typeof AppMusterilerRoute
  '/panel': typeof AppPanelRoute
  '/satis': typeof AppSatisRoute
  '/tedarukculer': typeof AppTedarukculerRoute
  '/xercler': typeof AppXerclerRoute
  '/mallar/$id': typeof AppMallarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hesab-bloklu': typeof HesabBlokluRoute
  '/login': typeof LoginRoute
  '/qeydiyyat': typeof QeydiyyatRoute
  '/ayarlar': typeof AppAyarlarRoute
  '/borclar': typeof AppBorclarRoute
  '/gun-sonu': typeof AppGunSonuRoute
  '/hesabatlar': typeof AppHesabatlarRoute
  '/iscilar': typeof AppIscilarRoute
  '/mallar': typeof AppMallarRoute
  '/musteriler': typeof AppMusterilerRoute
  '/panel': typeof AppPanelRoute
  '/satis': typeof AppSatisRoute
  '/tedarukculer': typeof AppTedarukculerRoute
  '/xercler': typeof AppXerclerRoute
  '/mallar/$id': typeof AppMallarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/hesab-bloklu': typeof HesabBlokluRoute
  '/login': typeof LoginRoute
  '/qeydiyyat': typeof QeydiyyatRoute
  '/_app/ayarlar': typeof AppAyarlarRoute
  '/_app/borclar': typeof AppBorclarRoute
  '/_app/gun-sonu': typeof AppGunSonuRoute
  '/_app/hesabatlar': typeof AppHesabatlarRoute
  '/_app/iscilar': typeof AppIscilarRoute
  '/_app/mallar': typeof AppMallarRoute
  '/_app/musteriler': typeof AppMusterilerRoute
  '/_app/panel': typeof AppPanelRoute
  '/_app/satis': typeof AppSatisRoute
  '/_app/tedarukculer': typeof AppTedarukculerRoute
  '/_app/xercler': typeof AppXerclerRoute
  '/_app/mallar_/$id': typeof AppMallarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hesab-bloklu'
    | '/login'
    | '/qeydiyyat'
    | '/ayarlar'
    | '/borclar'
    | '/gun-sonu'
    | '/hesabatlar'
    | '/iscilar'
    | '/mallar'
    | '/musteriler'
    | '/panel'
    | '/satis'
    | '/tedarukculer'
    | '/xercler'
    | '/mallar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/hesab-bloklu'
    | '/login'
    | '/qeydiyyat'
    | '/ayarlar'
    | '/borclar'
    | '/gun-sonu'
    | '/hesabatlar'
    | '/iscilar'
    | '/mallar'
    | '/musteriler'
    | '/panel'
    | '/satis'
    | '/tedarukculer'
    | '/xercler'
    | '/mallar/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/hesab-bloklu'
    | '/login'
    | '/qeydiyyat'
    | '/_app/ayarlar'
    | '/_app/borclar'
    | '/_app/gun-sonu'
    | '/_app/hesabatlar'
    | '/_app/iscilar'
    | '/_app/mallar'
    | '/_app/musteriler'
    | '/_app/panel'
    | '/_app/satis'
    | '/_app/tedarukculer'
    | '/_app/xercler'
    | '/_app/mallar_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  HesabBlokluRoute: typeof HesabBlokluRoute
  LoginRoute: typeof LoginRoute
  QeydiyyatRoute: typeof QeydiyyatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qeydiyyat': {
      id: '/qeydiyyat'
      path: '/qeydiyyat'
      fullPath: '/qeydiyyat'
      preLoaderRoute: typeof QeydiyyatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesab-bloklu': {
      id: '/hesab-bloklu'
      path: '/hesab-bloklu'
      fullPath: '/hesab-bloklu'
      preLoaderRoute: typeof HesabBlokluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/xercler': {
      id: '/_app/xercler'
      path: '/xercler'
      fullPath: '/xercler'
      preLoaderRoute: typeof AppXerclerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tedarukculer': {
      id: '/_app/tedarukculer'
      path: '/tedarukculer'
      fullPath: '/tedarukculer'
      preLoaderRoute: typeof AppTedarukculerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis': {
      id: '/_app/satis'
      path: '/satis'
      fullPath: '/satis'
      preLoaderRoute: typeof AppSatisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/panel': {
      id: '/_app/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AppPanelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/musteriler': {
      id: '/_app/musteriler'
      path: '/musteriler'
      fullPath: '/musteriler'
      preLoaderRoute: typeof AppMusterilerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mallar': {
      id: '/_app/mallar'
      path: '/mallar'
      fullPath: '/mallar'
      preLoaderRoute: typeof AppMallarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iscilar': {
      id: '/_app/iscilar'
      path: '/iscilar'
      fullPath: '/iscilar'
      preLoaderRoute: typeof AppIscilarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hesabatlar': {
      id: '/_app/hesabatlar'
      path: '/hesabatlar'
      fullPath: '/hesabatlar'
      preLoaderRoute: typeof AppHesabatlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gun-sonu': {
      id: '/_app/gun-sonu'
      path: '/gun-sonu'
      fullPath: '/gun-sonu'
      preLoaderRoute: typeof AppGunSonuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borclar': {
      id: '/_app/borclar'
      path: '/borclar'
      fullPath: '/borclar'
      preLoaderRoute: typeof AppBorclarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ayarlar': {
      id: '/_app/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AppAyarlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mallar_/$id': {
      id: '/_app/mallar_/$id'
      path: '/mallar/$id'
      fullPath: '/mallar/$id'
      preLoaderRoute: typeof AppMallarIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAyarlarRoute: typeof AppAyarlarRoute
  AppBorclarRoute: typeof AppBorclarRoute
  AppGunSonuRoute: typeof AppGunSonuRoute
  AppHesabatlarRoute: typeof AppHesabatlarRoute
  AppIscilarRoute: typeof AppIscilarRoute
  AppMallarRoute: typeof AppMallarRoute
  AppMusterilerRoute: typeof AppMusterilerRoute
  AppPanelRoute: typeof AppPanelRoute
  AppSatisRoute: typeof AppSatisRoute
  AppTedarukculerRoute: typeof AppTedarukculerRoute
  AppXerclerRoute: typeof AppXerclerRoute
  AppMallarIdRoute: typeof AppMallarIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAyarlarRoute: AppAyarlarRoute,
  AppBorclarRoute: AppBorclarRoute,
  AppGunSonuRoute: AppGunSonuRoute,
  AppHesabatlarRoute: AppHesabatlarRoute,
  AppIscilarRoute: AppIscilarRoute,
  AppMallarRoute: AppMallarRoute,
  AppMusterilerRoute: AppMusterilerRoute,
  AppPanelRoute: AppPanelRoute,
  AppSatisRoute: AppSatisRoute,
  AppTedarukculerRoute: AppTedarukculerRoute,
  AppXerclerRoute: AppXerclerRoute,
  AppMallarIdRoute: AppMallarIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  HesabBlokluRoute: HesabBlokluRoute,
  LoginRoute: LoginRoute,
  QeydiyyatRoute: QeydiyyatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
